<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class empleados extends Seeder
{
    /**
     * Run the database seeds.
     */
    protected $connection = 'mysql'; //bd concentradora
    public function run(): void
    {
        DB::table('empleados')->insert([
            [
                'id_empleado' => 1,
                'n_empleado' => 'TOYC00208',
                'nombres' => 'Michell Aldair',
                'apellido_p' => 'Bonilla',
                'apellido_m' => 'Uitz',
                'fecha_nacimiento' => '1994-11-14',
                'fecha_ingreso' => '2017-12-21',
                'rfc' => 'BOUM9411148M2',
                'curp' => 'BOUM941114HYNNTC04',
                'nss' => '05000000000',
                'correo_personal' => 'aldair@gmail.com',
                'celular_personal' => '9999999999',
                'id_tipo_asociado' => 1,
                'id_puesto' => 1,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-30 14:38:45',
                'created_user' => null,
                'updated_at' => null,
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 2,
                'n_empleado' => 'TOYAL0133',
                'nombres' => 'EDUIN AMILCAR',
                'apellido_p' => 'MAY',
                'apellido_m' => 'UC',
                'fecha_nacimiento' => '1995-10-17',
                'fecha_ingreso' => '2023-08-01',
                'rfc' => 'MAUE951017L43',
                'curp' => 'MAUE951017HYNYCD01',
                'nss' => '38169508520',
                'correo_personal' => null,
                'celular_personal' => '999999999',
                'id_tipo_asociado' => 1,
                'id_puesto' => 1,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-30 14:43:04',
                'created_user' => null,
                'updated_at' => null,
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 3,
                'n_empleado' => 'TOYM00056',
                'nombres' => 'ADRIANA ISABEL',
                'apellido_p' => 'HERNANDEZ',
                'apellido_m' => 'HERNANDEZ',
                'fecha_nacimiento' => '1977-09-23',
                'fecha_ingreso' => '2006-06-22',
                'rfc' => 'HEHA770923LL3',
                'curp' => 'HEHA770923MHGRRD07',
                'nss' => '68937716766',
                'correo_personal' => null,
                'celular_personal' => null,
                'id_tipo_asociado' => 1,
                'id_puesto' => 2,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-30 14:45:18',
                'created_user' => null,
                'updated_at' => '2024-07-30 14:45:23',
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 4,
                'n_empleado' => 'PRA00001',
                'nombres' => 'DANIEL',
                'apellido_p' => ' ',
                'apellido_m' => ' ',
                'fecha_nacimiento' => '2000-01-01',
                'fecha_ingreso' => '2024-07-15',
                'rfc' => 'XXXXXXXXXX',
                'curp' => 'XXXXXXXXXXXXXXXXXX',
                'nss' => '00000000000',
                'correo_personal' => null,
                'celular_personal' => null,
                'id_tipo_asociado' => 4,
                'id_puesto' => 15,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-30 14:48:54',
                'created_user' => null,
                'updated_at' => '2024-07-30 15:28:19',
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 5,
                'n_empleado' => 'TOYC00116',
                'nombres' => 'JARSEN ORLANDO',
                'apellido_p' => 'LEON',
                'apellido_m' => 'SOLIS',
                'fecha_nacimiento' => '1986-01-14',
                'fecha_ingreso' => '2014-04-01',
                'rfc' => 'LESJ860114224',
                'curp' => 'LESJ860114HQRNLR02',
                'nss' => '82058637032',
                'correo_personal' => null,
                'celular_personal' => '9983296525',
                'id_tipo_asociado' => 1,
                'id_puesto' => 4,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-31 19:57:39',
                'created_user' => null,
                'updated_at' => '2024-07-31 19:58:07',
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 6,
                'n_empleado' => 'TOYM00381',
                'nombres' => 'RAUL OCTAVIO DAVID',
                'apellido_p' => 'SALAZAR',
                'apellido_m' => 'CONTRERAS',
                'fecha_nacimiento' => '1979-05-12',
                'fecha_ingreso' => '2021-04-19',
                'rfc' => 'SACR790512FY8',
                'curp' => 'SACR790512HYNLNL09',
                'nss' => '84047905934',
                'correo_personal' => '',
                'celular_personal' => '',
                'id_tipo_asociado' => 1,
                'id_puesto' => 3,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-31 21:24:55',
                'created_user' => null,
                'updated_at' => null,
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 7,
                'n_empleado' => 'TOYM00424',
                'nombres' => 'ROMAN ADOLFO',
                'apellido_p' => 'YAMA',
                'apellido_m' => 'CASTILLO',
                'fecha_nacimiento' => '1985-08-09',
                'fecha_ingreso' => '2022-11-16',
                'rfc' => 'YACR850809L40',
                'curp' => 'YACR850809HYNMSM19',
                'nss' => '84128506338',
                'correo_personal' => null,
                'celular_personal' => '',
                'id_tipo_asociado' => 1,
                'id_puesto' => 4,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-31 21:26:09',
                'created_user' => null,
                'updated_at' => null,
                'updated_user' => null,
                'status' => 1,
            ],
            [
                'id_empleado' => 8,
                'n_empleado' => 'TOYM00063',
                'nombres' => 'ADRIAN EZAEL',
                'apellido_p' => 'HOIL',
                'apellido_m' => 'PECH',
                'fecha_nacimiento' => '1983-03-03',
                'fecha_ingreso' => '2012-01-04',
                'rfc' => 'HOPA830303DW6',
                'curp' => 'HOPA830303HYNLCD01',
                'nss' => '84088300136',
                'correo_personal' => null,
                'celular_personal' => '',
                'id_tipo_asociado' => 1,
                'id_puesto' => 4,
                'observaciones' => null,
                'fecha_baja' => null,
                'motivo_baja' => null,
                'created_at' => '2024-07-31 21:28:23',
                'created_user' => null,
                'updated_at' => null,
                'updated_user' => null,
                'status' => 1,
            ],
        ]);
    }
}
