
services:
  - type: web
    name: vigilancia-prt
    env: php
    php_version: "8.2"
    branch: main
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: https://tu-dominio.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nombre_de_tu_base_de_datos
      - key: DB_USERNAME
        value: usuario_bd
      - key: DB_PASSWORD
        value: contraseña_bd
