
services:
  - type: web
    name: vigilancia-prt
    env: php
    plan: free
    buildCommand: "composer install && npm install && npm run build && php artisan key:generate"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    autoDeploy: true
    branch: main
